### ISSUE TITLE
hash variable is not defined

### ISSUE THREAD

**Issue by manubb** [kapouer/window-page#25]
The `hash` variable used [here](https://github.com/kapouer/window-page/blob/1.1.3/index.js#L39) is not defined. It should probably be replaced with `obj.hash`.

**Comment by kapouer** [comment]
Already fixed in https://github.com/kapouer/window-page/commit/e8dd7084b5b6636f81b2d1325b8272f7a648c972

**Comment by manubb** [comment]
Ok. Saw this. The last published version is 1.1.3 which has the bug. Could you publish an updated version?

**Comment by kapouer** [comment]
Sure ! Will do asap.

**Comment by kapouer** [comment]
Published in version 1.1.4
